runtime: go111
instance_class: F1
automatic_scaling:
  max_instances: 2
  max_idle_instances: 1
  max_concurrent_requests: 80
  target_cpu_utilization: 0.9

handlers:
- url: /.well-known
  static_dir: well-known

- url: /js
  static_dir: js

- url: /.*
  script: auto
